### ISSUE TITLE
Cancel - Subscription

### ISSUE THREAD

**Issue by amanpreet-dev** [stripe-samples/subscription-use-cases#25]
How can we cancel a subscription at a particular time?
Platform -  NodeJS
Code I have used is - 
`const cancelSubscription = await stripe.subscriptions.del(StripeSubscriptionId);`

It cancels the subscription immediately. What is the way to cancel it at the end of period?
Do we have to pass that thing at the time of `Creating Subscription` or at the time of Cancellation?

**Comment by cjavilla-stripe** [comment]
Hey amanpreet-dev. Instead of cancelling the subscription with stripe.subscriptions.del, you would update the Subscription and set `cancel_at_period_end` https://stripe.com/docs/api/subscriptions/update#update_subscription-cancel_at_period_end 

You can set that at any point while a subscription is not cancelled already.
