### ISSUE TITLE
Incorrect upcoming invoice calculations

### ISSUE THREAD

**Issue by silviogutierrez** [stripe-samples/subscription-use-cases#29]
# Bug report

## Describe the bug

The documentation here shows how to compute the `immediate_total` and `next_invoice_sum` amounts.

However, the logic is incorrect when using discounts.

See here: https://stripe.com/docs/billing/subscriptions/per-seat#change-price

## To Reproduce

1. Create a subscription with per-seat licensing and tiers.
2. Create a customer and subscribe them to said subscription with a quantity of X.
3. Attach a discount/coupon to this subscription. Make it 100% for simplicity.
4. Recreate the code sample from the documentation, *making sure* to increase the quantity from `X` to `X+1` for the upcoming invoice preview.

## Expected behavior

Per the code sample and the 100% discount, I would expect both `immediate_total` and `next_invoice_sum` to both be zero. However, code sample will produce the right `immediate_total` of **0** but will *not* produce the right `next_invoice_sum` as the discount will be ignored.

Why? Because the logic loops over the line items of each invoice, and those don't reflect any discount.

Possible solution that works for me: `next_invoice_sum` = `invoice.total - immediate_total`. But I don't know how reliable this is.
## Additional context

I checked the sample for all languages.

**Comment by hideokamoto-stripe** [comment]
Hello,
This issue seems to be not a sample of this repository, but rather feedback related to Stripe Docs. Feedback regarding Stripe Docs can be submitted through the "Was this page helpful?" section located at the bottom of the page. You can directly send feedback to the Document team, so please make use of it.

<img width="438" alt="スクリーンショット 2024-04-25 17 02 19" src="https://github.com/stripe-samples/subscription-use-cases/assets/95597878/ed5f6cc2-8652-4a21-9c99-c0cbc3183182">

Thank you.
