### ISSUE TITLE
split into 3 different Stripe Samples

### ISSUE THREAD

**Issue by cjavilla-stripe** [stripe-samples/subscription-use-cases#76]
Nothing is re-used, having all the code in here is more confusing than helpful.

**Comment by efrazier** [comment]
How is this completed? I find already that the cli install is missing files from the git project and the paths are also based on that. For example, `seed.json` isn't added on the CLI install. 

`stripe samples create subscription-use-cases`

there is no seed.json

The path in package.json is 

```
"scripts": {
    "start": "node server/node/server.js",  but should be "server/server.js" (as that is what the CLI creates)
    "test": "echo \"Error: no test specified\" && exit 1"
  },

```

This makes me wonder if anyone is using these scripts without major changes or just to get some hints on API usage, which frankly seems more clear in the API docs.  I think part of the problem is related to too many things being bundled in one place, it gets confusing for everyone. But it these issues could be still resolved and you could stay on this path as well. 

When I do run `npm start` I get this

![image](https://github.com/user-attachments/assets/604f34af-3296-4717-9480-ba66a1b0fcaf)

Which I expect is another path issue.  

Will keep trying and post a new full report case, but just wondering if there is any air in this project in general.
