### ISSUE TITLE
Payment method is left attached to customer if subscription.status incomplete

### ISSUE THREAD

**Issue by turtlehat** [stripe-samples/subscription-use-cases#88]
If stripe.subscriptions.create is successful but has a status of incomplete then it returns to the client to call stripe.confirmCardPayment. But at this point if the user abandons the purchase they're left with a unused payment method attached to their customer.

If stripe.confirmCardPayment also fails the user can submit the form again which creates a new payment method on the client (stripe.createPaymentMethod). On the server the new payment method is attached to the customer (payment_method.attach). Now the user has two new payment methods attached to their customer but one of them unused.

Is there a way to prevent the unused payment methods remaining attached to the customer?

**Comment by cjavilla-stripe** [comment]
Thanks for reaching out @turtlehat. 

A PaymentMethod must be attached to the customer to attempt to start a paid subscription. If you want to detatch a payment method from a customer because an invoice failed, you could listen for a webhook and use the detatch API: https://stripe.com/docs/api/payment_methods/detach
