### ISSUE TITLE
"Error fetching sandbox." at demo 

### ISSUE THREAD

**Issue by jha-sudo** [stripe-samples/subscription-use-cases#96]
# Bug report

## Describe the bug
"Error fetching sandbox" at demo

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'https://v211e.sse.codesandbox.io/'
2. See error "Error fetching sandbox"
3. Forking does not resolve.

## Screenshots

![image](https://user-images.githubusercontent.com/69402749/110196541-2f6bbb80-7e13-11eb-824b-0a315c8fb835.png)

## System information

- OS: [e.g. macOS, Windows] Windows 10
- Browser (if applies) [e.g. chrome, safari] Version 88.0.4324.190 (Official Build) (64-bit)
- Server environment [e.g. Go, Java, Node, PHP, Python, Ruby, TypeScript]

**Comment by expressIndustries** [comment]
This has been broken for months.  Please fix.

**Comment by cjavilla-stripe** [comment]
The way our repos are setup doesn't work well with code sandbox. We've removed links and replaced with a gif so you can get a sense for how the sample works.

**Comment by expressIndustries** [comment]
Great.  You guys should try running the samples.  There are a few things
that aren’t setup right out of the box.  Stripe is supposed to be SIMPLE to
implement and integrate, right?  Make sure your samples / examples / demos
- are simple too!

On March 29, 2021 at 11:04:59 AM, CJ Avilla ***@***.***)
wrote:

Closed #96
<https://github.com/stripe-samples/subscription-use-cases/issues/96>.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/stripe-samples/subscription-use-cases/issues/96#event-4523049598>,
or unsubscribe
